'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'Cards',
      [
        {
          english: 'Apple',
          russian: 'Яблоко',
          learned: false,
          userId: 1,
          themeId: 1,
          imagePath: '/images/apple.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Banana',
          russian: 'Банан',
          learned: false,
          userId: 1,
          themeId: 1,
          imagePath: '/images/banana.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Orange',
          russian: 'Апельсин',
          learned: false,
          userId: 1,
          themeId: 1,
          imagePath: '/images/car.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Grapes',
          russian: 'Виноград',
          learned: false,
          userId: 2,
          themeId: 1,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Strawberry',
          russian: 'Клубника',
          learned: false,
          userId: 2,
          themeId: 1,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Car',
          russian: 'Машина',
          learned: false,
          userId: 2,
          themeId: 2,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Bicycle',
          russian: 'Велосипед',
          learned: false,
          userId: 2,
          themeId: 2,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Airplane',
          russian: 'Самолёт',
          learned: false,
          userId: 2,
          themeId: 2,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Bus',
          russian: 'Автобус',
          learned: false,
          userId: 2,
          themeId: 2,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Train',
          russian: 'Поезд',
          learned: false,
          userId: 2,
          themeId: 2,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Cat',
          russian: 'Кошка',
          learned: false,
          userId: 2,
          themeId: 3,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Dog',
          russian: 'Собака',
          learned: false,
          userId: 2,
          themeId: 3,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Elephant',
          russian: 'Слон',
          learned: false,
          userId: 2,
          themeId: 3,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Tiger',
          russian: 'Тигр',
          learned: false,
          userId: 2,
          themeId: 3,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Dolphin',
          russian: 'Дельфин',
          learned: false,
          userId: 2,
          themeId: 3,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Teacher',
          russian: 'Учитель',
          learned: false,
          userId: 2,
          themeId: 4,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Doctor',
          russian: 'Врач',
          learned: false,
          userId: 2,
          themeId: 4,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Engineer',
          russian: 'Инженер',
          learned: false,
          userId: 2,
          themeId: 4,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Programmer',
          russian: 'Программист',
          learned: false,
          userId: 2,
          themeId: 4,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Chef',
          russian: 'Повар',
          learned: false,
          userId: 2,
          themeId: 4,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Football',
          russian: 'Футбол',
          learned: false,
          userId: 2,
          themeId: 5,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Basketball',
          russian: 'Баскетбол',
          learned: false,
          userId: 2,
          themeId: 5,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Swimming',
          russian: 'Плавание',
          learned: false,
          userId: 2,
          themeId: 5,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Tennis',
          russian: 'Теннис',
          learned: false,
          userId: 2,
          themeId: 5,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Running',
          russian: 'Бег',
          learned: false,
          userId: 2,
          themeId: 5,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Red',
          russian: 'Красный',
          learned: false,
          userId: 2,
          themeId: 6,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Blue',
          russian: 'Синий',
          learned: false,
          userId: 2,
          themeId: 6,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Green',
          russian: 'Зелёный',
          learned: false,
          userId: 2,
          themeId: 6,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Yellow',
          russian: 'Жёлтый',
          learned: false,
          userId: 2,
          themeId: 6,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Black',
          russian: 'Чёрный',
          learned: false,
          userId: 2,
          themeId: 6,
          imagePath: '/images/dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Cards', null, {});
  },
};
